### ISSUE TITLE
Video in README doesn't load properly

### ISSUE THREAD

**Issue by PerzotProgrammer** [sentemon/MessagingPlatform#2]
While browsing your repository, I noticed that your video showing the application in action is not loading properly.
Browser: Google Chrome
OS: Windows 11 23H2
<hr>

![image](https://github.com/user-attachments/assets/81658cad-c077-4192-9390-bda57f248dfc)
<hr>

I suggest changing the video extension from mov to mp4 for better compatibility.

PS Wielki szacun dla ciebie jeżeli budowałeś tą aplikacje samemu bez żadnych tutoriali. 
Widać, że trafiłeś na odpowiedni kierunek w swoim życiu ^_~
Jesteś kotem!

**Comment by PerzotProgrammer** [comment]
I have analyzed this further and I realized that the video is not in HTML video tag but in img tag
<hr>
![image](https://github.com/user-attachments/assets/8fa4c27b-de25-4063-b6e0-f98066ebd23d)
<hr>
This could potentially fix the issue

**Comment by sentemon** [comment]
Thanks for this issue. The problem was that I previously displayed the case in GIF format, which is why I used the img tag. After switching to video, it still worked fine in my browser, probably due to caching or something else. In any case, I've already fixed it.

PS: dzieki, fajny mecz dzis mieliscie na wf-ie :)

**Comment by sentemon** [comment]
However, the problem seems to be due to the file size, as it is not displaying at all now

**Comment by PerzotProgrammer** [comment]
In that case, I suggest sending video onto external file hosting and linking it from there or linking it directly from files in repository.
Github most likely has some restrictions on files in comments, md files etc.

**Comment by sentemon** [comment]
done
